//! Inference adapters — `run_tracker` / `run_stt` / `run_audio_analysis`.
//!
//! Each adapter owns the runtime wiring for one algorithm class and returns
//! the *canonical data struct that the corresponding `verbreel-state` verb
//! already publishes* — `TrackerRunData`, `CaptionAutoGenerateData`,
//! `AudioAnalyzeData`. The composition layer calls an adapter, then hands
//! the returned struct back to the state verb's success path. This keeps
//! the result shape owned by `verbreel-state` (single source of truth) and
//! avoids a parallel data vocabulary in `verbreel-ai`.
//!
//! ## Dependency direction
//!
//! `verbreel-ai → verbreel-state` (per `CLAUDE.md`). Adapters import the
//! state data structs; no state verb imports an adapter. The adapters are
//! *additive* runtime surface the composition root invokes — wiring them in
//! does not change any state verb's pure `compute_patch` output, so the
//! conformance fixtures stay frozen.
//!
//! ## Cache-first, then runtime
//!
//! Every adapter takes a [`ModelCacheKey`] so the composition layer can
//! check the on-disk cache before paying for inference. On a miss, the
//! adapter loads the model (`ort` session or Python sidecar). Real
//! inference requires the ONNX Runtime / Python deps, which are not part of
//! the build-time floor — when they are unavailable the adapter surfaces a
//! loud [`AiError`] rather than fabricating an empty result (Linus rule).

use serde_json::json;
use verbreel_state::{AudioAnalyzeData, CaptionAutoGenerateData, TrackerRunData};

use crate::error::AiError;
use crate::model::ModelCacheKey;
use crate::sidecar::{SidecarRequest, run_sidecar};

/// Resolved inference backend for an adapter call.
///
/// The composition root chooses the backend per the [`crate::registry`]
/// entry's `sidecar` flag and passes it down, so the adapter does not
/// re-derive routing.
#[derive(Debug, Clone)]
pub enum Backend {
    /// In-process ONNX Runtime model at the given path.
    Ort {
        /// Absolute path to the `.onnx` model file.
        model_path: std::path::PathBuf,
    },
    /// Out-of-process Python sidecar: program + argv.
    Sidecar {
        /// Sidecar interpreter / binary (e.g. `/usr/bin/python3`).
        program: String,
        /// Sidecar argv (e.g. the script path).
        args: Vec<String>,
    },
}

/// Run the tracker algorithm and return the canonical [`TrackerRunData`].
///
/// `tracker_id` and the resolved analysis window are echoed by the caller
/// into the returned struct; this adapter produces the inference-derived
/// fields (`sample_count`, `mean_confidence`, `bbox_trace_summary`).
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] when the `ort` runtime is
/// unavailable (feature-off or missing `libonnxruntime`), or
/// [`AiError::SidecarLaunchFailed`] / [`AiError::ProcessExited`] /
/// [`AiError::SidecarProtocol`] for a sidecar-backed tracker.
pub fn run_tracker(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    tracker_id: &str,
) -> Result<TrackerRunData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            // ort inference path: opening the session is the gate that
            // fails loudly when the runtime is absent. Folding per-frame
            // BBox samples into a `TrackerRunData` needs shipped model
            // assets (out of scope for this slice), so a present runtime
            // still returns a loud, distinct error rather than a fake trace.
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "tracker `{tracker_id}` ort backbone inference requires shipped model \
                     assets; gated until those land"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("tracker", json!({ "tracker_id": tracker_id }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_tracker(tracker_id, &response.result)
        }
    }
}

/// Run speech-to-text and return the canonical [`CaptionAutoGenerateData`].
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for an `ort`-backed model when the
/// runtime is unavailable, or the sidecar error variants for the
/// faster-whisper sidecar path.
pub fn run_stt(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    language_hint: Option<&str>,
) -> Result<CaptionAutoGenerateData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: "stt ort backend requires shipped model assets; gated until those land"
                    .to_string(),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("stt", json!({ "language": language_hint }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_stt(&response.result)
        }
    }
}

/// Run audio analysis and return the canonical [`AudioAnalyzeData`].
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for an `ort`-backed analyzer when
/// the runtime is unavailable, or the sidecar error variants for the
/// `BeatNet` sidecar path.
pub fn run_audio_analysis(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    target_id: &str,
) -> Result<AudioAnalyzeData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "audio analysis for target `{target_id}` ort backend requires shipped model \
                     assets; gated until those land"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("audio_analysis", json!({ "target": target_id }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_audio_analysis(target_id, &response.result)
        }
    }
}

/// Runtime gate for the `ort` backend. Returns `Ok(())` only when the ONNX
/// Runtime is actually loadable for `model_path`; otherwise the matching
/// [`AiError::ModelLoadFailed`] is surfaced. Single chokepoint so the three
/// adapters share one runtime gate with identical error semantics across
/// feature states. Feature-on it opens then drops a session (the open is
/// the gate); feature-off it reports the runtime as unavailable.
fn ensure_ort_runtime(model_path: &std::path::Path) -> Result<(), AiError> {
    #[cfg(feature = "ort")]
    {
        crate::session::OrtSession::open(model_path)?;
        Ok(())
    }
    #[cfg(not(feature = "ort"))]
    {
        let _ = model_path;
        Err(crate::session::open_unavailable())
    }
}

/// Decode a sidecar tracker result into [`TrackerRunData`].
fn decode_tracker(tracker_id: &str, result: &serde_json::Value) -> Result<TrackerRunData, AiError> {
    serde_json::from_value::<TrackerRunData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("tracker `{tracker_id}` sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar STT result into [`CaptionAutoGenerateData`].
fn decode_stt(result: &serde_json::Value) -> Result<CaptionAutoGenerateData, AiError> {
    serde_json::from_value::<CaptionAutoGenerateData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("stt sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar audio-analysis result into [`AudioAnalyzeData`].
fn decode_audio_analysis(
    target_id: &str,
    result: &serde_json::Value,
) -> Result<AudioAnalyzeData, AiError> {
    serde_json::from_value::<AudioAnalyzeData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("audio analysis `{target_id}` sidecar result decode failed: {err}"),
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ModelId, ModelVersion};
    use std::io::Write as _;
    use verbreel_types::AssetHash;

    const ASSET: &str = "aa11bb22cc33dd44ee55ff66001122334455667788990011223344556677889900";

    fn cache_key(model: &str) -> ModelCacheKey {
        ModelCacheKey {
            model_id: ModelId::new(model),
            model_version: ModelVersion::new("v1"),
            source_asset_hash: AssetHash::new(&ASSET[..64]).unwrap(),
            params_hash: [1u8; 32],
            result_schema_version: 1,
        }
    }

    #[test]
    fn ort_backend_surfaces_model_load_failed_when_runtime_unavailable() {
        // Feature-off, `ensure_ort_runtime` short-circuits before touching
        // `ort`. Feature-on, the `runtime_available` probe reports the
        // (absent) runtime as unavailable and returns ModelLoadFailed
        // without entering ort's deadlocking lazy init. Either way the
        // adapter must surface ModelLoadFailed, never hang.
        let key = cache_key("mixformer_v2_s");
        let backend = Backend::Ort {
            model_path: std::path::PathBuf::from("/nonexistent/model.onnx"),
        };
        let err = run_tracker(&key, &backend, "tk-1").unwrap_err();
        assert!(
            matches!(err, AiError::ModelLoadFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn sidecar_stt_decodes_canonical_struct_via_real_python() {
        // Sidecar emits a CaptionAutoGenerateData-shaped result; the adapter
        // must deserialize it into the state-owned canonical struct.
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("stt.py");
        let track_id = "0192a000-0000-7000-8000-000000000abc";
        let mut f = std::fs::File::create(&script).unwrap();
        write!(
            f,
            r#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({{"op": "stt", "result": {{
    "text_track_id": "{track_id}",
    "segments": [],
    "detected_language": "en"
}}}}))
"#,
        )
        .unwrap();

        let key = cache_key("whisper");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data = run_stt(&key, &backend, Some("en")).expect("stt round-trip");
        assert_eq!(data.detected_language, "en");
        assert!(data.segments.is_empty());
    }

    #[test]
    fn sidecar_malformed_result_surfaces_protocol_error() {
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("bad.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({"op": "stt", "result": {"unexpected": True}}))
"#,
        )
        .unwrap();

        let key = cache_key("whisper");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let err = run_stt(&key, &backend, None).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarProtocol { .. }),
            "got {err:?}"
        );
    }
}
