//! Inference adapters — `run_tracker` / `run_stt` / `run_audio_analysis`.
//!
//! Each adapter owns the runtime wiring for one algorithm class and returns
//! the *canonical data struct that the corresponding `verbreel-state` verb
//! already publishes* — `TrackerRunData`, `CaptionAutoGenerateData`,
//! `AudioAnalyzeData`. The intended caller is the composition layer (cli /
//! mcp / http): it calls an adapter, then hands the returned struct back to
//! the state verb's success path. This keeps the result shape owned by
//! `verbreel-state` (single source of truth) and avoids a parallel data
//! vocabulary in `verbreel-ai`. As with [`crate::registry`], that caller is
//! a deferred follow-up slice — no cli / mcp / http path invokes an adapter
//! yet, so outside the crate's own tests these entrypoints have no caller.
//!
//! ## Dependency direction
//!
//! `verbreel-ai → verbreel-state` (per `CLAUDE.md`). Adapters import the
//! state data structs; no state verb imports an adapter. The adapters are
//! *additive* runtime surface — wiring them into a composition root does not
//! change any state verb's pure `compute_patch` output, so the conformance
//! fixtures stay frozen.
//!
//! ## Cache-first, then runtime
//!
//! Every adapter takes a [`ModelCacheKey`] so the composition layer can
//! check the on-disk cache before paying for inference. On a miss, the
//! adapter loads the model (`ort` session or Python sidecar). Real
//! inference requires the ONNX Runtime / Python deps, which are not part of
//! the build-time floor — when they are unavailable the adapter surfaces a
//! loud [`AiError`] rather than fabricating an empty result (Linus rule).

use serde_json::json;
use verbreel_state::{
    AudioAnalyzeData, CaptionAutoGenerateData, FaceMouthTrace, GenImageData, SegmentMatteRef,
    TrackerRunData,
};

use crate::error::AiError;
use crate::model::ModelCacheKey;
use crate::sidecar::{SidecarRequest, run_sidecar};

/// Resolved inference backend for an adapter call.
///
/// The composition root chooses the backend per the [`crate::registry`]
/// entry's `sidecar` flag and passes it down, so the adapter does not
/// re-derive routing.
#[derive(Debug, Clone)]
pub enum Backend {
    /// In-process ONNX Runtime model at the given path.
    Ort {
        /// Absolute path to the `.onnx` model file.
        model_path: std::path::PathBuf,
    },
    /// Out-of-process Python sidecar: program + argv.
    Sidecar {
        /// Sidecar interpreter / binary (e.g. `/usr/bin/python3`).
        program: String,
        /// Sidecar argv (e.g. the script path).
        args: Vec<String>,
    },
}

/// Run the tracker algorithm and return the canonical [`TrackerRunData`].
///
/// The sidecar supplies every field of the returned struct — including
/// `tracker_id`, `cache_path`, and `cache_hit`, not just the
/// inference-derived `sample_count` / `mean_confidence` / `bbox_trace_summary`
/// — and [`decode_tracker`] deserializes the whole struct verbatim. The
/// `tracker_id` argument is forwarded into the sidecar request and used to
/// frame decode errors; the adapter does not overwrite the decoded fields
/// with it, so the sidecar owns the cache-identity fields end to end.
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] when the `ort` runtime is
/// unavailable (feature-off or missing `libonnxruntime`), or
/// [`AiError::SidecarLaunchFailed`] / [`AiError::ProcessExited`] /
/// [`AiError::SidecarProtocol`] for a sidecar-backed tracker.
pub fn run_tracker(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    tracker_id: &str,
) -> Result<TrackerRunData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            // ort inference path: opening the session is the gate that
            // fails loudly when the runtime is absent. Folding per-frame
            // BBox samples into a `TrackerRunData` needs shipped model
            // assets (out of scope for this slice), so a present runtime
            // still returns a loud, distinct error rather than a fake trace.
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "tracker `{tracker_id}` ort backbone inference requires shipped model \
                     assets; gated until those land"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("tracker", json!({ "tracker_id": tracker_id }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_tracker(tracker_id, &response.result)
        }
    }
}

/// Run speech-to-text and return the canonical [`CaptionAutoGenerateData`].
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for an `ort`-backed model when the
/// runtime is unavailable, or the sidecar error variants for the
/// faster-whisper sidecar path.
pub fn run_stt(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    language_hint: Option<&str>,
) -> Result<CaptionAutoGenerateData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: "stt ort backend requires shipped model assets; gated until those land"
                    .to_string(),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("stt", json!({ "language": language_hint }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_stt(&response.result)
        }
    }
}

/// Run audio analysis and return the canonical [`AudioAnalyzeData`].
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for an `ort`-backed analyzer when
/// the runtime is unavailable, or the sidecar error variants for the
/// `BeatNet` sidecar path.
pub fn run_audio_analysis(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    target_id: &str,
) -> Result<AudioAnalyzeData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "audio analysis for target `{target_id}` ort backend requires shipped model \
                     assets; gated until those land"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new("audio_analysis", json!({ "target": target_id }));
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_audio_analysis(target_id, &response.result)
        }
    }
}

/// Run the `face_mouth` perception pass and return the canonical
/// [`FaceMouthTrace`] (issue #474 — auto-director perception floor).
///
/// For each tracked face the sidecar returns a `bbox_trace` (for
/// auto-reframe) and a `mouth_open_trace` (Mouth Aspect Ratio, for
/// downstream active-speaker inference). `analysis_id` is forwarded into the
/// sidecar params so the sidecar owns the cache identity (same contract as
/// `tracker_id` for [`run_tracker`]); `video_path` names the source clip the
/// sidecar decodes (required by the #474 wire contract — the reference
/// sidecar hard-fails without it); `max_faces` and `sample_fps` are the
/// per-call tuning knobs. The `ort` arm is a loud, gated error path —
/// `MediaPipe` Face Mesh has no shipped `ort` backbone, so it never
/// fabricates a trace.
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for the (gated) `ort` arm, or
/// [`AiError::SidecarLaunchFailed`] / [`AiError::ProcessExited`] /
/// [`AiError::SidecarProtocol`] for the sidecar path.
pub fn run_face_mouth(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    analysis_id: &str,
    video_path: &str,
    max_faces: u32,
    sample_fps: u32,
) -> Result<FaceMouthTrace, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            // No ort backbone ships for MediaPipe Face Mesh; the open is the
            // runtime gate, and a present runtime still returns a loud,
            // distinct error rather than a fabricated trace.
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "face_mouth analysis `{analysis_id}` has no ort backbone; runs via the \
                     MediaPipe Python sidecar only"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new(
                "face_mouth",
                json!({
                    "analysis_id": analysis_id,
                    "video_path": video_path,
                    "max_faces": max_faces,
                    "sample_fps": sample_fps,
                }),
            );
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_face_mouth(analysis_id, &response.result)
        }
    }
}

/// Run the `segment` subject-segmentation pass and return the canonical
/// [`SegmentMatteRef`] (issue #476 — green-screen-free background removal).
///
/// The sidecar produces a per-frame foreground alpha matte and freezes it as
/// a single content-addressed `image`-kind asset; the returned reference
/// names that asset by [`AssetHash`](verbreel_state::AssetHash) plus the
/// matte dimensions and per-frame timing. `analysis_id` is forwarded into the
/// sidecar params so the sidecar owns the cache identity (same contract as
/// `analysis_id` for [`run_face_mouth`]); `video_path` names the source clip
/// the sidecar decodes (required by the #476 wire contract — the reference
/// sidecar hard-fails without it). The ML pass runs once and the matte stays
/// frozen, so render is byte-deterministic — never per-render inference.
///
/// The `ort` arm is a loud, gated error path — the segmentation models
/// (`MediaPipe` Selfie / `RVM` / `MODNet` / `BiRefNet`) have no shipped `ort`
/// backbone, so it never fabricates an empty matte.
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for the (gated) `ort` arm, or
/// [`AiError::SidecarLaunchFailed`] / [`AiError::ProcessExited`] /
/// [`AiError::SidecarProtocol`] for the sidecar path.
pub fn run_segment(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    analysis_id: &str,
    video_path: &str,
) -> Result<SegmentMatteRef, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            // No ort backbone ships for the segmentation models; the open is
            // the runtime gate, and a present runtime still returns a loud,
            // distinct error rather than a fabricated matte.
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: format!(
                    "segment analysis `{analysis_id}` has no ort backbone; runs via the \
                     segmentation Python sidecar only"
                ),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new(
                "segment",
                json!({
                    "analysis_id": analysis_id,
                    "video_path": video_path,
                }),
            );
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_segment(analysis_id, &response.result)
        }
    }
}

/// Run text-to-image generation and return the canonical [`GenImageData`]
/// (issue #482 — generative replacement-background floor).
///
/// The sidecar runs an operator-installed diffusion model (SDXL / Flux-class
/// or API-backed — the engine ships no weights and pins no vendor) with the
/// given `prompt`, `seed`, and target `width` / `height`, writes the produced
/// image to a temp file, and returns that path plus the honored seed. The
/// composition root then imports the path through the content-addressed
/// `asset.import` path (the CAS write stays in `verbreel-state`; this adapter
/// only returns the handle). `seed` is the explicit reproducibility knob —
/// same prompt + params + seed → identical image bytes → identical CAS hash
/// (the engine's existing `seed` rule for particle/glitch effects).
///
/// The `ort` arm is a loud, gated error path — no diffusion `ort` backbone
/// ships, so it never fabricates an image.
///
/// # Errors
///
/// Returns [`AiError::ModelLoadFailed`] for the (gated) `ort` arm, or
/// [`AiError::SidecarLaunchFailed`] / [`AiError::ProcessExited`] /
/// [`AiError::SidecarProtocol`] for the sidecar path.
pub fn run_gen_image(
    cache_key: &ModelCacheKey,
    backend: &Backend,
    prompt: &str,
    seed: u64,
    width: u32,
    height: u32,
) -> Result<GenImageData, AiError> {
    let _ = cache_key;
    match backend {
        Backend::Ort { model_path } => {
            // No ort backbone ships for the diffusion models; the open is the
            // runtime gate, and a present runtime still returns a loud,
            // distinct error rather than a fabricated image.
            ensure_ort_runtime(model_path)?;
            Err(AiError::ModelLoadFailed {
                detail: "gen_image has no ort backbone; runs via the diffusion Python sidecar only"
                    .to_string(),
            })
        }
        Backend::Sidecar { program, args } => {
            let request = SidecarRequest::new(
                "gen_image",
                json!({
                    "prompt": prompt,
                    "seed": seed,
                    "width": width,
                    "height": height,
                }),
            );
            let argv: Vec<&str> = args.iter().map(String::as_str).collect();
            let response = run_sidecar(program, &argv, &request)?;
            decode_gen_image(&response.result)
        }
    }
}

/// Runtime gate for the `ort` backend. Returns `Ok(())` only when the ONNX
/// Runtime is actually loadable for `model_path`; otherwise the matching
/// [`AiError::ModelLoadFailed`] is surfaced. Single chokepoint so the three
/// adapters share one runtime gate with identical error semantics across
/// feature states. Feature-on it opens then drops a session (the open is
/// the gate); feature-off it reports the runtime as unavailable.
fn ensure_ort_runtime(model_path: &std::path::Path) -> Result<(), AiError> {
    #[cfg(feature = "ort")]
    {
        crate::session::OrtSession::open(model_path)?;
        Ok(())
    }
    #[cfg(not(feature = "ort"))]
    {
        let _ = model_path;
        Err(crate::session::open_unavailable())
    }
}

/// Decode a sidecar tracker result into [`TrackerRunData`].
fn decode_tracker(tracker_id: &str, result: &serde_json::Value) -> Result<TrackerRunData, AiError> {
    serde_json::from_value::<TrackerRunData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("tracker `{tracker_id}` sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar STT result into [`CaptionAutoGenerateData`].
fn decode_stt(result: &serde_json::Value) -> Result<CaptionAutoGenerateData, AiError> {
    serde_json::from_value::<CaptionAutoGenerateData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("stt sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar audio-analysis result into [`AudioAnalyzeData`].
fn decode_audio_analysis(
    target_id: &str,
    result: &serde_json::Value,
) -> Result<AudioAnalyzeData, AiError> {
    serde_json::from_value::<AudioAnalyzeData>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("audio analysis `{target_id}` sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar `face_mouth` result into [`FaceMouthTrace`].
///
/// No silent fallback: a malformed payload surfaces
/// [`AiError::SidecarProtocol`], never an empty trace.
fn decode_face_mouth(
    analysis_id: &str,
    result: &serde_json::Value,
) -> Result<FaceMouthTrace, AiError> {
    serde_json::from_value::<FaceMouthTrace>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("face_mouth `{analysis_id}` sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar `segment` result into [`SegmentMatteRef`].
///
/// No silent fallback: a malformed payload surfaces
/// [`AiError::SidecarProtocol`], never an empty matte.
fn decode_segment(
    analysis_id: &str,
    result: &serde_json::Value,
) -> Result<SegmentMatteRef, AiError> {
    serde_json::from_value::<SegmentMatteRef>(result.clone()).map_err(|err| {
        AiError::SidecarProtocol {
            detail: format!("segment `{analysis_id}` sidecar result decode failed: {err}"),
        }
    })
}

/// Decode a sidecar `gen_image` result into [`GenImageData`].
///
/// No silent fallback: a malformed payload surfaces
/// [`AiError::SidecarProtocol`], never a fabricated image handle.
fn decode_gen_image(result: &serde_json::Value) -> Result<GenImageData, AiError> {
    serde_json::from_value::<GenImageData>(result.clone()).map_err(|err| AiError::SidecarProtocol {
        detail: format!("gen_image sidecar result decode failed: {err}"),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ModelId, ModelVersion};
    use std::io::Write as _;
    use verbreel_state::AudioAnalysisTargetKind;
    use verbreel_types::{AssetHash, Tick};

    const ASSET: &str = "aa11bb22cc33dd44ee55ff66001122334455667788990011223344556677889900";

    fn cache_key(model: &str) -> ModelCacheKey {
        ModelCacheKey {
            model_id: ModelId::new(model),
            model_version: ModelVersion::new("v1"),
            source_asset_hash: AssetHash::new(&ASSET[..64]).unwrap(),
            params_hash: [1u8; 32],
            result_schema_version: 1,
        }
    }

    #[test]
    fn ort_backend_surfaces_model_load_failed_when_runtime_unavailable() {
        // Feature-off, `ensure_ort_runtime` short-circuits before touching
        // `ort`. Feature-on, the `runtime_available` probe reports the
        // (absent) runtime as unavailable and returns ModelLoadFailed
        // without entering ort's deadlocking lazy init. Either way the
        // adapter must surface ModelLoadFailed, never hang.
        let key = cache_key("mixformer_v2_s");
        let backend = Backend::Ort {
            model_path: std::path::PathBuf::from("/nonexistent/model.onnx"),
        };
        let err = run_tracker(&key, &backend, "tk-1").unwrap_err();
        assert!(
            matches!(err, AiError::ModelLoadFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn sidecar_stt_decodes_canonical_struct_via_real_python() {
        // Sidecar emits a CaptionAutoGenerateData-shaped result; the adapter
        // must deserialize it into the state-owned canonical struct.
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("stt.py");
        let track_id = "0192a000-0000-7000-8000-000000000abc";
        let mut f = std::fs::File::create(&script).unwrap();
        write!(
            f,
            r#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({{"op": "stt", "result": {{
    "text_track_id": "{track_id}",
    "segments": [],
    "detected_language": "en"
}}}}))
"#,
        )
        .unwrap();

        let key = cache_key("whisper");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data = run_stt(&key, &backend, Some("en")).expect("stt round-trip");
        assert_eq!(data.detected_language, "en");
        assert!(data.segments.is_empty());
    }

    #[test]
    fn sidecar_audio_analysis_decodes_canonical_struct_via_real_python() {
        // Sidecar emits an AudioAnalyzeData-shaped result; the adapter must
        // deserialize it into the state-owned canonical struct. Guards the
        // `op` string ("audio_analysis") and struct type against copy-paste
        // drift from the stt/tracker arms.
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("audio_analysis.py");
        let target_id = "0192a000-0000-7000-8000-000000000def";
        let mut f = std::fs::File::create(&script).unwrap();
        write!(
            f,
            r#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({{"op": "audio_analysis", "result": {{
    "target_id": "{target_id}",
    "target_kind": "clip",
    "features_returned": ["tempo"],
    "tempo_bpm": 120.0,
    "cache_path": "/cache/audio/{target_id}.json",
    "cache_hit": False
}}}}))
"#,
        )
        .unwrap();

        let key = cache_key("beatnet");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data =
            run_audio_analysis(&key, &backend, target_id).expect("audio-analysis round-trip");
        assert_eq!(data.target_id, target_id);
        assert_eq!(data.target_kind, AudioAnalysisTargetKind::Clip);
        assert_eq!(data.features_returned, vec!["tempo".to_string()]);
        assert_eq!(data.tempo_bpm, Some(120.0));
        assert!(!data.cache_hit);
    }

    #[test]
    fn sidecar_malformed_result_surfaces_protocol_error() {
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("bad.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({"op": "stt", "result": {"unexpected": True}}))
"#,
        )
        .unwrap();

        let key = cache_key("whisper");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let err = run_stt(&key, &backend, None).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarProtocol { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn sidecar_face_mouth_decodes_canonical_struct_via_real_python() {
        // Stub child validates the REQUEST contract (op == face_mouth, params
        // carry the required video_path) then prints a FIXED face_mouth
        // payload — no mediapipe required. The request-side assert keeps the
        // adapter and the reference sidecar from silently drifting apart
        // (the reference sidecar hard-fails without params.video_path).
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("face_mouth.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
req = json.loads(sys.stdin.readline())
assert req["op"] == "face_mouth", req["op"]
assert req["params"]["video_path"] == "assets/aa/sha.mp4", req["params"]
print(json.dumps({"op": "face_mouth", "result": {"faces": [
    {"speaker_id": "f0",
     "bbox_trace": [{"t_tk": 0, "x": 120, "y": 80, "w": 300, "h": 300}],
     "mouth_open_trace": [{"t_tk": 0, "mar": 0.04}]}
]}}))
"#,
        )
        .unwrap();

        let key = cache_key("face_mouth");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data = run_face_mouth(&key, &backend, "an-1", "assets/aa/sha.mp4", 4, 15)
            .expect("face_mouth round-trip");
        assert_eq!(data.faces.len(), 1);
        let face = &data.faces[0];
        assert_eq!(face.speaker_id, "f0");
        assert_eq!(face.bbox_trace.len(), 1);
        assert_eq!(face.bbox_trace[0].t_tk, Tick::new(0));
        assert_eq!(face.bbox_trace[0].x, 120);
        assert_eq!(face.bbox_trace[0].w, 300);
        assert_eq!(face.mouth_open_trace.len(), 1);
        assert!((face.mouth_open_trace[0].mar - 0.04).abs() < f64::EPSILON);
    }

    #[test]
    fn face_mouth_malformed_result_surfaces_protocol_error() {
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("bad_face_mouth.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({"op": "face_mouth", "result": {"unexpected": True}}))
"#,
        )
        .unwrap();

        let key = cache_key("face_mouth");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let err = run_face_mouth(&key, &backend, "an-1", "assets/aa/sha.mp4", 4, 15).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarProtocol { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn face_mouth_missing_binary_surfaces_launch_failed() {
        let key = cache_key("face_mouth");
        let backend = Backend::Sidecar {
            program: "/nonexistent/python-binary".to_string(),
            args: vec![],
        };
        let err = run_face_mouth(&key, &backend, "an-1", "assets/aa/sha.mp4", 4, 15).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarLaunchFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn face_mouth_nonzero_exit_surfaces_process_exited() {
        let key = cache_key("face_mouth");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec!["-c".to_string(), "import sys; sys.exit(3)".to_string()],
        };
        let err = run_face_mouth(&key, &backend, "an-1", "assets/aa/sha.mp4", 4, 15).unwrap_err();
        assert!(matches!(err, AiError::ProcessExited { .. }), "got {err:?}");
    }

    #[test]
    fn face_mouth_ort_backend_surfaces_model_load_failed() {
        let key = cache_key("face_mouth");
        let backend = Backend::Ort {
            model_path: std::path::PathBuf::from("/nonexistent/model.onnx"),
        };
        let err = run_face_mouth(&key, &backend, "an-1", "assets/aa/sha.mp4", 4, 15).unwrap_err();
        assert!(
            matches!(err, AiError::ModelLoadFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn sidecar_segment_decodes_canonical_struct_via_real_python() {
        // Stub child validates the REQUEST contract (op == segment, params
        // carry the required video_path) then prints a FIXED matte payload —
        // no segmentation model required. The request-side assert keeps the
        // adapter and the reference sidecar from silently drifting apart (the
        // reference sidecar hard-fails without params.video_path).
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("segment.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
req = json.loads(sys.stdin.readline())
assert req["op"] == "segment", req["op"]
assert req["params"]["video_path"] == "assets/aa/sha.mp4", req["params"]
print(json.dumps({"op": "segment", "result": {
    "matte_asset_hash": "aa11bb22cc33dd44ee55ff660011223344556677889900112233445566778899",
    "width": 1920,
    "height": 1080,
    "frames": [{"t_tk": 0}, {"t_tk": 8000}]
}}))
"#,
        )
        .unwrap();

        let key = cache_key("segment");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data =
            run_segment(&key, &backend, "an-1", "assets/aa/sha.mp4").expect("segment round-trip");
        assert_eq!(data.matte_asset_hash.as_str().len(), 64);
        assert_eq!(data.width, 1920);
        assert_eq!(data.height, 1080);
        assert_eq!(data.frames.len(), 2);
        assert_eq!(data.frames[0].t_tk, Tick::new(0));
        assert_eq!(data.frames[1].t_tk, Tick::new(8000));
    }

    #[test]
    fn segment_malformed_result_surfaces_protocol_error() {
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("bad_segment.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({"op": "segment", "result": {"unexpected": True}}))
"#,
        )
        .unwrap();

        let key = cache_key("segment");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let err = run_segment(&key, &backend, "an-1", "assets/aa/sha.mp4").unwrap_err();
        assert!(
            matches!(err, AiError::SidecarProtocol { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn segment_missing_binary_surfaces_launch_failed() {
        let key = cache_key("segment");
        let backend = Backend::Sidecar {
            program: "/nonexistent/python-binary".to_string(),
            args: vec![],
        };
        let err = run_segment(&key, &backend, "an-1", "assets/aa/sha.mp4").unwrap_err();
        assert!(
            matches!(err, AiError::SidecarLaunchFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn segment_nonzero_exit_surfaces_process_exited() {
        let key = cache_key("segment");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec!["-c".to_string(), "import sys; sys.exit(3)".to_string()],
        };
        let err = run_segment(&key, &backend, "an-1", "assets/aa/sha.mp4").unwrap_err();
        assert!(matches!(err, AiError::ProcessExited { .. }), "got {err:?}");
    }

    #[test]
    fn segment_ort_backend_surfaces_model_load_failed() {
        let key = cache_key("segment");
        let backend = Backend::Ort {
            model_path: std::path::PathBuf::from("/nonexistent/model.onnx"),
        };
        let err = run_segment(&key, &backend, "an-1", "assets/aa/sha.mp4").unwrap_err();
        assert!(
            matches!(err, AiError::ModelLoadFailed { .. }),
            "got {err:?}"
        );
    }

    /// Stub child that asserts the `gen_image` REQUEST contract (op,
    /// prompt, echoed seed, dims) and prints a FIXED image handle. The
    /// request-side asserts keep the adapter and the reference sidecar from
    /// drifting apart (the reference sidecar requires `prompt` + `seed`).
    /// No real diffusion model is required.
    fn write_gen_image_stub(dir: &std::path::Path) -> std::path::PathBuf {
        let script = dir.join("gen_image.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
req = json.loads(sys.stdin.readline())
assert req["op"] == "gen_image", req["op"]
assert req["params"]["prompt"] == "a misty forest at dawn", req["params"]
seed = req["params"]["seed"]
print(json.dumps({"op": "gen_image", "result": {
    "image_path": "/tmp/vr-gen/%d.png" % seed,
    "width": req["params"]["width"],
    "height": req["params"]["height"],
    "seed": seed
}}))
"#,
        )
        .unwrap();
        script
    }

    #[test]
    fn sidecar_gen_image_decodes_canonical_struct_via_real_python() {
        let dir = tempfile::tempdir().unwrap();
        let script = write_gen_image_stub(dir.path());

        let key = cache_key("gen_image");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let data = run_gen_image(&key, &backend, "a misty forest at dawn", 42, 1024, 768)
            .expect("gen_image round-trip");
        assert_eq!(data.image_path, "/tmp/vr-gen/42.png");
        assert_eq!(data.width, 1024);
        assert_eq!(data.height, 768);
        assert_eq!(data.seed, 42);
    }

    #[test]
    fn gen_image_same_seed_yields_identical_result() {
        // Determinism: same prompt + seed + dims → identical decoded result
        // (the seed is the reproducibility knob; the stub echoes it into the
        // handle so a seed mismatch would diverge the path).
        let dir = tempfile::tempdir().unwrap();
        let script = write_gen_image_stub(dir.path());
        let key = cache_key("gen_image");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let first = run_gen_image(&key, &backend, "a misty forest at dawn", 7, 512, 512).unwrap();
        let second = run_gen_image(&key, &backend, "a misty forest at dawn", 7, 512, 512).unwrap();
        assert_eq!(first, second);
        assert_eq!(first.seed, 7);
    }

    #[test]
    fn gen_image_malformed_result_surfaces_protocol_error() {
        let dir = tempfile::tempdir().unwrap();
        let script = dir.path().join("bad_gen_image.py");
        let mut f = std::fs::File::create(&script).unwrap();
        f.write_all(
            br#"import sys, json
json.loads(sys.stdin.readline())
print(json.dumps({"op": "gen_image", "result": {"unexpected": True}}))
"#,
        )
        .unwrap();

        let key = cache_key("gen_image");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec![script.to_str().unwrap().to_string()],
        };
        let err = run_gen_image(&key, &backend, "p", 1, 8, 8).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarProtocol { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn gen_image_missing_binary_surfaces_launch_failed() {
        let key = cache_key("gen_image");
        let backend = Backend::Sidecar {
            program: "/nonexistent/python-binary".to_string(),
            args: vec![],
        };
        let err = run_gen_image(&key, &backend, "p", 1, 8, 8).unwrap_err();
        assert!(
            matches!(err, AiError::SidecarLaunchFailed { .. }),
            "got {err:?}"
        );
    }

    #[test]
    fn gen_image_nonzero_exit_surfaces_process_exited() {
        let key = cache_key("gen_image");
        let backend = Backend::Sidecar {
            program: "/usr/bin/python3".to_string(),
            args: vec!["-c".to_string(), "import sys; sys.exit(3)".to_string()],
        };
        let err = run_gen_image(&key, &backend, "p", 1, 8, 8).unwrap_err();
        assert!(matches!(err, AiError::ProcessExited { .. }), "got {err:?}");
    }

    #[test]
    fn gen_image_ort_backend_surfaces_model_load_failed() {
        let key = cache_key("gen_image");
        let backend = Backend::Ort {
            model_path: std::path::PathBuf::from("/nonexistent/model.onnx"),
        };
        let err = run_gen_image(&key, &backend, "p", 1, 8, 8).unwrap_err();
        assert!(
            matches!(err, AiError::ModelLoadFailed { .. }),
            "got {err:?}"
        );
    }
}
