//! Tests for `caption.auto_generate` (§10.1) — ninety-first production verb.

use std::sync::Arc;

use serde_json::{Value, json};
use verbreel_state::verbs::caption_auto_generate::compute_patch;
use verbreel_state::verbs::text_add::StyleArg;
use verbreel_state::{
    CaptionAutoGenerateArgs, CaptionAutoGenerateData, CaptionAutoGenerateError,
    CaptionAutoGenerateSegment, CaptionAutoGenerateVerb, Project, Verb, VerbError, VerbRegistry,
    default_fixtures, default_registry, validate_reconstructors,
};
use verbreel_types::{ClipId, ProjectId, TrackId};

#[cfg(feature = "native")]
use verbreel_state::{LifecycleError, ProjectStore};

const EMPTY_FIXTURE: &str = include_str!("fixtures/empty_project_create.json");
const FIXTURE_PROJECT_ID: &str = "0190b8d3-15e3-7000-bd00-000000000001";
const AUDIO_TRACK_SELECTOR: &str = "track:audio[0]";
const TEXT_TRACK_ID: &str = "0190b8d3-15e3-7000-bd00-0000000aa911";
const SEGMENT_CLIP_ID: &str = "0190b8d3-15e3-7000-bd00-0000000bb911";

fn empty_project() -> Project {
    serde_json::from_str(EMPTY_FIXTURE).expect("empty fixture -> Project")
}

fn fixture_project_id() -> ProjectId {
    empty_project().id
}

fn id<T>(raw: &str) -> T
where
    T: std::str::FromStr,
    T::Err: std::fmt::Debug,
{
    raw.parse().expect("hard-coded UUIDv7 parses")
}

fn args_default() -> CaptionAutoGenerateArgs {
    CaptionAutoGenerateArgs {
        project_id: fixture_project_id(),
        from_selector: AUDIO_TRACK_SELECTOR.to_string(),
        language: None,
        style: None,
        max_line_chars: None,
        to_track: None,
        model: None,
    }
}

fn args_value() -> Value {
    json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
    })
}

#[test]
fn args_deserialize_ok_with_all_fields() {
    let raw = json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
        "language": "en-US",
        "style": { "font_family": "Inter", "font_size_px": 24.0 },
        "max_line_chars": 42,
        "to_track": "track:0190b8d3-15e3-7000-bd00-0000000aa912",
        "model": "large-v3",
    });
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(raw).expect("args parse");

    assert_eq!(typed.project_id.to_string(), FIXTURE_PROJECT_ID);
    assert_eq!(typed.from_selector, AUDIO_TRACK_SELECTOR);
    assert_eq!(typed.language.as_deref(), Some("en-US"));
    assert_eq!(typed.max_line_chars, Some(42));
    assert_eq!(
        typed.to_track.as_deref(),
        Some("track:0190b8d3-15e3-7000-bd00-0000000aa912")
    );
    assert_eq!(typed.model.as_deref(), Some("large-v3"));
}

#[test]
fn args_deserialize_ok_with_omitted_optionals() {
    let typed: CaptionAutoGenerateArgs =
        serde_json::from_value(args_value()).expect("minimal args parse");
    assert_eq!(typed.project_id.to_string(), FIXTURE_PROJECT_ID);
    assert_eq!(typed.from_selector, AUDIO_TRACK_SELECTOR);
    assert_eq!(typed.language, None);
    assert_eq!(typed.style, None);
    assert_eq!(typed.max_line_chars, None);
    assert_eq!(typed.to_track, None);
    assert_eq!(typed.model, None);
}

#[test]
fn args_serde_rename_maps_from_to_from_selector() {
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(args_value()).expect("args parse");
    assert_eq!(typed.from_selector, AUDIO_TRACK_SELECTOR);
}

#[test]
fn style_preset_string_parses() {
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
        "style": "subtitle_default",
    }))
    .expect("args parse");

    assert_eq!(
        typed.style,
        Some(StyleArg::Preset("subtitle_default".to_string()))
    );
}

#[test]
fn style_object_parses() {
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
        "style": { "font_size_px": 28.0, "color": "#ffffffff" },
    }))
    .expect("args parse");

    match typed.style {
        Some(StyleArg::Object(map)) => {
            assert_eq!(map.get("font_size_px"), Some(&json!(28.0)));
            assert_eq!(map.get("color"), Some(&json!("#ffffffff")));
        }
        other => panic!("expected StyleArg::Object, got {other:?}"),
    }
}

#[test]
fn args_missing_required_fields_fail_through_verb() {
    let prior = empty_project();
    let verb = CaptionAutoGenerateVerb;

    for payload in [
        json!({ "from": AUDIO_TRACK_SELECTOR }),
        json!({ "project_id": FIXTURE_PROJECT_ID }),
    ] {
        let err = verb
            .compute_patch(&prior, &payload)
            .expect_err("missing required arg maps to BadArgs");
        assert!(matches!(err, VerbError::BadArgs { .. }));
    }
}

#[test]
fn args_unknown_field_rejected_through_verb() {
    let prior = empty_project();
    let verb = CaptionAutoGenerateVerb;
    let err = verb
        .compute_patch(
            &prior,
            &json!({
                "project_id": FIXTURE_PROJECT_ID,
                "from": AUDIO_TRACK_SELECTOR,
                "extra": true,
            }),
        )
        .expect_err("deny_unknown_fields rejects extra key");

    assert!(matches!(err, VerbError::BadArgs { .. }));
}

#[test]
fn model_accepts_arbitrary_string_at_args_layer() {
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
        "model": "custom-local-model-v1",
    }))
    .expect("args parse");

    assert_eq!(typed.model.as_deref(), Some("custom-local-model-v1"));
}

#[test]
fn max_line_chars_accepts_integer_at_args_layer() {
    let typed: CaptionAutoGenerateArgs = serde_json::from_value(json!({
        "project_id": FIXTURE_PROJECT_ID,
        "from": AUDIO_TRACK_SELECTOR,
        "max_line_chars": 88,
    }))
    .expect("args parse");

    assert_eq!(typed.max_line_chars, Some(88));
}

#[test]
fn segment_data_shape_serializes() {
    let segment = CaptionAutoGenerateSegment {
        clip_id: id::<ClipId>(SEGMENT_CLIP_ID),
        start_tk: 12_000,
        end_tk_exclusive: 24_000,
        text: "hello".to_string(),
    };

    let value = serde_json::to_value(&segment).expect("segment serializes");
    assert_eq!(
        value,
        json!({
            "clip_id": SEGMENT_CLIP_ID,
            "start_tk": 12_000,
            "end_tk_exclusive": 24_000,
            "text": "hello",
        })
    );
}

#[test]
fn success_data_shape_serializes() {
    let data = CaptionAutoGenerateData {
        text_track_id: id::<TrackId>(TEXT_TRACK_ID),
        segments: vec![CaptionAutoGenerateSegment {
            clip_id: id::<ClipId>(SEGMENT_CLIP_ID),
            start_tk: 0,
            end_tk_exclusive: 1_000,
            text: "line".to_string(),
        }],
        detected_language: "en".to_string(),
    };

    let value = serde_json::to_value(&data).expect("data serializes");
    assert_eq!(value["text_track_id"], json!(TEXT_TRACK_ID));
    assert_eq!(value["detected_language"], json!("en"));
    assert_eq!(value["segments"][0]["clip_id"], json!(SEGMENT_CLIP_ID));
}

#[test]
fn compute_patch_always_returns_busy_for_well_formed_args() {
    let prior = empty_project();
    let args = args_default();
    let err = compute_patch(&prior, &args).expect_err("v1 floor always errors");
    assert!(matches!(err, CaptionAutoGenerateError::Busy { .. }));
}

#[test]
fn error_maps_to_custom_not_bad_args() {
    let prior = empty_project();
    let verb = CaptionAutoGenerateVerb;
    let err = verb
        .compute_patch(&prior, &args_value())
        .expect_err("v1 floor always errors");
    assert!(matches!(err, VerbError::Custom(_)));
}

#[test]
fn error_text_includes_e_busy() {
    let prior = empty_project();
    let args = args_default();
    let err = compute_patch(&prior, &args).expect_err("v1 floor always errors");
    assert!(err.to_string().contains("E_BUSY"));
}

#[test]
fn verb_custom_error_detail_contains_e_busy() {
    let prior = empty_project();
    let verb = CaptionAutoGenerateVerb;
    let err = verb
        .compute_patch(&prior, &args_value())
        .expect_err("v1 floor always errors");

    let VerbError::Custom(detail) = err else {
        panic!("expected Custom, got {err:?}");
    };
    assert!(detail.contains("E_BUSY"));
}

#[test]
fn error_path_is_project_agnostic() {
    let prior_a = empty_project();
    let mut prior_b = empty_project();
    prior_b.name = "different-name".to_string();
    prior_b.duration_tk = verbreel_types::Tick::new(9_876_543);

    let args = args_default();
    let err_a = compute_patch(&prior_a, &args).expect_err("a errors");
    let err_b = compute_patch(&prior_b, &args).expect_err("b errors");

    assert_eq!(err_a, err_b);
}

#[test]
fn reconstruct_returns_null_for_well_formed_args() {
    let verb = CaptionAutoGenerateVerb;
    let prior = empty_project();
    let data = verb
        .reconstruct(&args_value(), &json!([]), &[], &prior)
        .expect("reconstruct succeeds for typed args");
    assert_eq!(data, Value::Null);
}

#[test]
fn reconstruct_rejects_malformed_args() {
    let verb = CaptionAutoGenerateVerb;
    let prior = empty_project();
    let err = verb
        .reconstruct(&json!({}), &json!([]), &[], &prior)
        .expect_err("malformed args fail");
    let msg = err.to_string();
    assert!(
        msg.contains("CaptionAutoGenerateArgs") || msg.contains("wrong type"),
        "unexpected reconstruct error: {msg}",
    );
}

#[test]
fn default_fixture_validates_with_single_verb_registry() {
    let fixture = default_fixtures()
        .into_iter()
        .find(|event| event.verb == "caption.auto_generate")
        .expect("default_fixtures includes caption.auto_generate");

    let mut registry = VerbRegistry::new();
    registry
        .register(Arc::new(CaptionAutoGenerateVerb))
        .expect("register caption.auto_generate verb");

    let report = validate_reconstructors(&registry, &[fixture]).expect("fixture validates");
    assert_eq!(report.verbs_checked, vec!["caption.auto_generate"]);
    assert_eq!(report.fixtures_run, 1);
}

#[test]
fn default_fixture_has_empty_patch_warnings_and_null_expected_data() {
    let fixture = default_fixtures()
        .into_iter()
        .find(|event| event.verb == "caption.auto_generate")
        .expect("default_fixtures includes caption.auto_generate");

    assert_eq!(fixture.patch, json!([]));
    assert!(fixture.warnings.is_empty());
    assert_eq!(fixture.expected_data, Value::Null);
}

#[test]
fn default_registry_contains_caption_auto_generate() {
    let registry = default_registry();
    let verb = registry
        .get("caption.auto_generate")
        .expect("caption.auto_generate in default_registry");

    let prior = empty_project();
    let err = verb
        .compute_patch(&prior, &args_value())
        .expect_err("v1 floor always errors");

    let VerbError::Custom(detail) = err else {
        panic!("expected Custom, got {err:?}");
    };
    assert!(detail.contains("E_BUSY"));
}

#[cfg(feature = "native")]
#[test]
fn mutate_via_verb_route_returns_custom() {
    use tempfile::TempDir;

    let dir = TempDir::new().expect("tempdir");
    let mut store = ProjectStore::create_with_registry(
        dir.path(),
        empty_project(),
        &default_registry(),
        &default_fixtures(),
    )
    .expect("create_with_registry succeeds");

    let outcome = store.mutate_via_verb("caption.auto_generate", args_value(), None);
    let Err(LifecycleError::VerbExecutionFailed { source, .. }) = outcome else {
        panic!("expected VerbExecutionFailed, got {outcome:?}");
    };

    let VerbError::Custom(detail) = source else {
        panic!("expected Custom source, got {source:?}");
    };
    assert!(detail.contains("E_BUSY"));
}
