//! `audio.extract` (§9.1) — eighty-ninth production verb in the engine.
//!
//! ## v1 floor — always errors with `E_IO`.
//!
//! Extracting a video's audio stream requires codec decode, hashing the
//! generated bytes, writing a content-addressed asset, optionally placing
//! a timeline clip, and maintaining link groups. Those operations need a
//! storage/codec context outside the pure [`Verb::compute_patch`] contract.
//! Until that context exists, every well-formed call returns `E_IO` and no
//! patch, warnings, asset, clip, track, or link group are produced.
//!
//! ## Reconstructor framing for an always-errors verb.
//!
//! `compute_patch` always returns `Err`, so no successful event is written
//! for this verb in v1. The reconstructor still deserializes args for the
//! startup gate fixture and returns `Value::Null`, matching the always-error
//! floors used by the asset storage verbs.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;
use verbreel_types::{AssetId, ClipId, LinkGroupId, ProjectId, TrackId};

use crate::project::Project;
use crate::reconstructor::{ReconstructError, Verb, VerbError};

/// Codec requested for the extracted audio sidecar.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AudioExtractCodec {
    /// Lossless PCM samples wrapped in a WAV container.
    #[serde(rename = "pcm_s16le")]
    PcmS16Le,
    /// AAC audio wrapped in an M4A/MP4 container.
    #[serde(rename = "aac")]
    Aac,
}

impl AudioExtractCodec {
    /// Return the exact spec wire literal for this codec.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::PcmS16Le => "pcm_s16le",
            Self::Aac => "aac",
        }
    }
}

/// Arguments for `audio.extract`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AudioExtractArgs {
    /// Target project id.
    pub project_id: ProjectId,

    /// Source video clip id or selector.
    pub clip: String,

    /// Optional destination audio track selector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_track: Option<String>,

    /// Optional extraction codec. Omitted resolves to [`AudioExtractCodec::PcmS16Le`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codec: Option<AudioExtractCodec>,
}

/// Envelope `data` returned by a future successful `audio.extract`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AudioExtractData {
    /// Extracted audio asset id.
    pub asset_id: AssetId,

    /// Created audio clip id, present iff `to_track` was supplied.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clip_id: Option<ClipId>,

    /// Destination audio track id, present iff `to_track` was supplied.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub track_id: Option<TrackId>,

    /// Link group joined or created for the extracted clip, when a clip is created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link_group: Option<LinkGroupId>,
}

/// Verb-level errors for `audio.extract`.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum AudioExtractError {
    /// Codec/storage extraction is unavailable in the pure v1 floor.
    #[error("audio.extract: E_IO — {detail}")]
    Io {
        /// Human-readable runtime failure detail.
        detail: String,
    },
}

/// Resolve the omitted-codec default without changing the args wire shape.
#[must_use]
pub fn resolved_codec(args: &AudioExtractArgs) -> AudioExtractCodec {
    args.codec.unwrap_or(AudioExtractCodec::PcmS16Le)
}

/// Build the RFC 6902 patch for `audio.extract`.
///
/// v1 floor: always returns [`AudioExtractError::Io`].
///
/// # Errors
///
/// Always errors with [`AudioExtractError::Io`] in v1 because media codec
/// and content-addressed storage work cannot run inside the pure verb.
pub fn compute_patch(
    _prior: &Project,
    args: &AudioExtractArgs,
) -> Result<(Value, Vec<Value>, Value), AudioExtractError> {
    let codec = resolved_codec(args);
    Err(AudioExtractError::Io {
        detail: format!(
            "codec/storage VerbContext unavailable for codec `{}` in the v1 floor",
            codec.as_str()
        ),
    })
}

impl From<AudioExtractError> for VerbError {
    fn from(value: AudioExtractError) -> Self {
        match value {
            AudioExtractError::Io { .. } => VerbError::Custom(value.to_string()),
        }
    }
}

/// The §0.8 verb for `audio.extract`.
#[derive(Debug, Default)]
pub struct AudioExtractVerb;

impl Verb for AudioExtractVerb {
    fn verb(&self) -> &'static str {
        "audio.extract"
    }

    fn compute_patch(
        &self,
        prior: &Project,
        args: &Value,
    ) -> Result<(json_patch::Patch, Value, Vec<Value>), VerbError> {
        let typed: AudioExtractArgs =
            serde_json::from_value(args.clone()).map_err(|err| VerbError::BadArgs {
                detail: format!("audio.extract: args deserialize failed: {err}"),
            })?;

        match compute_patch(prior, &typed) {
            Ok((patch_value, warnings, data)) => {
                let patch: json_patch::Patch =
                    serde_json::from_value(patch_value).map_err(|err| {
                        VerbError::Custom(format!(
                            "audio.extract: patch construction failed: {err}"
                        ))
                    })?;
                Ok((patch, data, warnings))
            }
            Err(err) => Err(err.into()),
        }
    }

    fn reconstruct(
        &self,
        args: &Value,
        _patch: &Value,
        _warnings: &[Value],
        _post_state: &Project,
    ) -> Result<Value, ReconstructError> {
        let _typed: AudioExtractArgs =
            serde_json::from_value(args.clone()).map_err(|_| ReconstructError::TypeMismatch {
                name: "args",
                expected: "AudioExtractArgs",
            })?;

        Ok(Value::Null)
    }
}
