//! `caption.auto_generate` (§10.1) — ninety-first production verb.
//!
//! ## v1 floor — always errors with `E_BUSY`.
//!
//! Real auto-caption generation requires long-running streaming runtime
//! plumbing (audio decode, model invocation, progress emission, and
//! dry-run wiring) that does not belong in the pure
//! [`Verb::compute_patch`] contract yet. Until that runtime lands,
//! every well-formed call returns `E_BUSY` and no patch/warnings/data.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;
use verbreel_types::{ClipId, ProjectId, TrackId};

use crate::project::Project;
use crate::reconstructor::{ReconstructError, Verb, VerbError};
use crate::verbs::text_add::StyleArg;

/// Arguments for `caption.auto_generate`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CaptionAutoGenerateArgs {
    /// Target project id.
    pub project_id: ProjectId,
    /// Audio source selector (`track:...` or `clip:...` in the future runtime path).
    #[serde(rename = "from")]
    pub from_selector: String,
    /// Optional BCP-47 language tag.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Optional style preset string or partial text style object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<StyleArg>,
    /// Optional line-wrap hint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_line_chars: Option<u32>,
    /// Optional destination text-track selector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub to_track: Option<String>,
    /// Optional caption model override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

/// Segment row in the future successful `caption.auto_generate` response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptionAutoGenerateSegment {
    /// Emitted text clip id for this segment.
    pub clip_id: ClipId,
    /// Inclusive start tick on timeline.
    pub start_tk: i64,
    /// Exclusive end tick on timeline.
    pub end_tk_exclusive: i64,
    /// Segment text.
    pub text: String,
}

/// Envelope `data` for a future successful `caption.auto_generate` call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptionAutoGenerateData {
    /// Destination text-track id.
    pub text_track_id: TrackId,
    /// Generated transcription segments.
    pub segments: Vec<CaptionAutoGenerateSegment>,
    /// Echoed or auto-detected language tag.
    pub detected_language: String,
}

/// Verb-level runtime failures for `caption.auto_generate`.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum CaptionAutoGenerateError {
    /// Streaming caption generation runtime is unavailable in this slice.
    #[error("caption.auto_generate: E_BUSY — {detail}")]
    Busy {
        /// Human-readable runtime detail.
        detail: String,
    },
}

/// Build the RFC 6902 patch for `caption.auto_generate`.
///
/// v1 floor: always returns [`CaptionAutoGenerateError::Busy`].
///
/// # Errors
///
/// Always errors with [`CaptionAutoGenerateError::Busy`] in v1 because
/// writer-class streaming/AI runtime plumbing is intentionally deferred.
pub fn compute_patch(
    _prior: &Project,
    args: &CaptionAutoGenerateArgs,
) -> Result<(Value, Vec<Value>, CaptionAutoGenerateData), CaptionAutoGenerateError> {
    Err(CaptionAutoGenerateError::Busy {
        detail: format!(
            "writer-class streaming runtime unavailable in the v1 floor (from `{}`)",
            args.from_selector
        ),
    })
}

impl From<CaptionAutoGenerateError> for VerbError {
    fn from(value: CaptionAutoGenerateError) -> Self {
        match value {
            CaptionAutoGenerateError::Busy { .. } => VerbError::Custom(value.to_string()),
        }
    }
}

/// The §0.8 verb for `caption.auto_generate`.
#[derive(Debug, Default)]
pub struct CaptionAutoGenerateVerb;

impl Verb for CaptionAutoGenerateVerb {
    fn verb(&self) -> &'static str {
        "caption.auto_generate"
    }

    fn compute_patch(
        &self,
        prior: &Project,
        args: &Value,
    ) -> Result<(json_patch::Patch, Value, Vec<Value>), VerbError> {
        let typed: CaptionAutoGenerateArgs =
            serde_json::from_value(args.clone()).map_err(|err| VerbError::BadArgs {
                detail: format!("caption.auto_generate: args deserialize failed: {err}"),
            })?;

        match compute_patch(prior, &typed) {
            Ok((patch_value, warnings, data)) => {
                let patch: json_patch::Patch =
                    serde_json::from_value(patch_value).map_err(|err| {
                        VerbError::Custom(format!(
                            "caption.auto_generate: patch construction failed: {err}"
                        ))
                    })?;
                Ok((
                    patch,
                    serde_json::to_value(data).map_err(|err| {
                        VerbError::Custom(format!(
                            "caption.auto_generate: data serialization failed: {err}"
                        ))
                    })?,
                    warnings,
                ))
            }
            Err(err) => Err(err.into()),
        }
    }

    fn reconstruct(
        &self,
        args: &Value,
        _patch: &Value,
        _warnings: &[Value],
        _post_state: &Project,
    ) -> Result<Value, ReconstructError> {
        let _typed: CaptionAutoGenerateArgs =
            serde_json::from_value(args.clone()).map_err(|_| ReconstructError::TypeMismatch {
                name: "args",
                expected: "CaptionAutoGenerateArgs",
            })?;

        Ok(Value::Null)
    }
}
